/**
 * Mock patient data matching the PatientData type from src/types.ts.
 *
 * This replaces the upstream API so the app works fully offline with
 * realistic, deterministic data.
 */

import type { PatientData } from '../src/types';

const mockPatients: PatientData[] = [
  {
    name: 'Jessica Taylor',
    gender: 'Female',
    age: 28,
    profile_picture: '',
    date_of_birth: '08/23/1996',
    phone_number: '(415) 555-1234',
    emergency_contact: '(415) 555-5678',
    insurance_type: 'Sunrise Health Assurance',
    diagnosis_history: [
      {
        month: 'May',
        year: 2024,
        blood_pressure: { systolic: { value: 118, levels: 'Normal' }, diastolic: { value: 78, levels: 'Normal' } },
        heart_rate: { value: 72, levels: 'Normal' },
        respiratory_rate: { value: 16, levels: 'Normal' },
        temperature: { value: 98.2, levels: 'Normal' },
      },
      {
        month: 'June',
        year: 2024,
        blood_pressure: { systolic: { value: 122, levels: 'Elevated' }, diastolic: { value: 80, levels: 'Normal' } },
        heart_rate: { value: 74, levels: 'Normal' },
        respiratory_rate: { value: 17, levels: 'Normal' },
        temperature: { value: 98.4, levels: 'Normal' },
      },
      {
        month: 'July',
        year: 2024,
        blood_pressure: { systolic: { value: 126, levels: 'Elevated' }, diastolic: { value: 82, levels: 'Elevated' } },
        heart_rate: { value: 76, levels: 'Normal' },
        respiratory_rate: { value: 18, levels: 'Normal' },
        temperature: { value: 98.6, levels: 'Normal' },
      },
      {
        month: 'August',
        year: 2024,
        blood_pressure: { systolic: { value: 120, levels: 'Normal' }, diastolic: { value: 79, levels: 'Normal' } },
        heart_rate: { value: 70, levels: 'Normal' },
        respiratory_rate: { value: 16, levels: 'Normal' },
        temperature: { value: 98.1, levels: 'Normal' },
      },
      {
        month: 'September',
        year: 2024,
        blood_pressure: { systolic: { value: 132, levels: 'Elevated' }, diastolic: { value: 86, levels: 'Elevated' } },
        heart_rate: { value: 78, levels: 'Normal' },
        respiratory_rate: { value: 18, levels: 'Normal' },
        temperature: { value: 98.7, levels: 'Normal' },
      },
      {
        month: 'October',
        year: 2024,
        blood_pressure: { systolic: { value: 128, levels: 'Elevated' }, diastolic: { value: 84, levels: 'Elevated' } },
        heart_rate: { value: 75, levels: 'Normal' },
        respiratory_rate: { value: 17, levels: 'Normal' },
        temperature: { value: 98.5, levels: 'Normal' },
      },
      {
        month: 'November',
        year: 2024,
        blood_pressure: { systolic: { value: 124, levels: 'Elevated' }, diastolic: { value: 81, levels: 'Normal' } },
        heart_rate: { value: 73, levels: 'Normal' },
        respiratory_rate: { value: 16, levels: 'Normal' },
        temperature: { value: 98.3, levels: 'Normal' },
      },
      {
        month: 'December',
        year: 2024,
        blood_pressure: { systolic: { value: 130, levels: 'Elevated' }, diastolic: { value: 85, levels: 'Elevated' } },
        heart_rate: { value: 77, levels: 'Normal' },
        respiratory_rate: { value: 18, levels: 'Normal' },
        temperature: { value: 98.6, levels: 'Normal' },
      },
      {
        month: 'January',
        year: 2025,
        blood_pressure: { systolic: { value: 116, levels: 'Normal' }, diastolic: { value: 76, levels: 'Normal' } },
        heart_rate: { value: 71, levels: 'Normal' },
        respiratory_rate: { value: 15, levels: 'Normal' },
        temperature: { value: 98.0, levels: 'Normal' },
      },
      {
        month: 'February',
        year: 2025,
        blood_pressure: { systolic: { value: 134, levels: 'Elevated' }, diastolic: { value: 88, levels: 'Elevated' } },
        heart_rate: { value: 80, levels: 'Normal' },
        respiratory_rate: { value: 19, levels: 'Normal' },
        temperature: { value: 98.8, levels: 'Normal' },
      },
      {
        month: 'March',
        year: 2025,
        blood_pressure: { systolic: { value: 120, levels: 'Normal' }, diastolic: { value: 78, levels: 'Normal' } },
        heart_rate: { value: 72, levels: 'Normal' },
        respiratory_rate: { value: 16, levels: 'Normal' },
        temperature: { value: 98.2, levels: 'Normal' },
      },
      {
        month: 'April',
        year: 2025,
        blood_pressure: { systolic: { value: 126, levels: 'Elevated' }, diastolic: { value: 82, levels: 'Elevated' } },
        heart_rate: { value: 74, levels: 'Normal' },
        respiratory_rate: { value: 17, levels: 'Normal' },
        temperature: { value: 98.4, levels: 'Normal' },
      },
    ],
    diagnostic_list: [
      { name: 'Hypertension', description: 'Chronic high blood pressure', status: 'Under Observation' },
      { name: 'Type 2 Diabetes', description: 'Insulin resistance and elevated blood sugar', status: 'Under Observation' },
      { name: 'Asthma', description: 'Recurrent episodes of bronchial constriction', status: 'Stable' },
      { name: 'Seasonal Allergies', description: 'Allergic rhinitis triggered by pollen', status: 'Resolved' },
    ],
    lab_results: [
      'Blood Test - Complete Blood Count',
      'Blood Test - Lipid Panel',
      'Urinalysis',
      'Hemoglobin A1C',
      'Thyroid Function Test',
    ],
  },
  {
    name: 'Michael Johnson',
    gender: 'Male',
    age: 45,
    profile_picture: '',
    date_of_birth: '03/14/1980',
    phone_number: '(415) 555-9012',
    emergency_contact: '(415) 555-3456',
    insurance_type: 'Blue Shield Plus',
    diagnosis_history: [
      {
        month: 'May',
        year: 2024,
        blood_pressure: { systolic: { value: 140, levels: 'High' }, diastolic: { value: 92, levels: 'High' } },
        heart_rate: { value: 82, levels: 'Normal' },
        respiratory_rate: { value: 18, levels: 'Normal' },
        temperature: { value: 98.6, levels: 'Normal' },
      },
      {
        month: 'June',
        year: 2024,
        blood_pressure: { systolic: { value: 138, levels: 'High' }, diastolic: { value: 90, levels: 'High' } },
        heart_rate: { value: 80, levels: 'Normal' },
        respiratory_rate: { value: 17, levels: 'Normal' },
        temperature: { value: 98.4, levels: 'Normal' },
      },
      {
        month: 'July',
        year: 2024,
        blood_pressure: { systolic: { value: 142, levels: 'High' }, diastolic: { value: 94, levels: 'High' } },
        heart_rate: { value: 84, levels: 'Normal' },
        respiratory_rate: { value: 19, levels: 'Normal' },
        temperature: { value: 98.7, levels: 'Normal' },
      },
      {
        month: 'August',
        year: 2024,
        blood_pressure: { systolic: { value: 136, levels: 'High' }, diastolic: { value: 88, levels: 'Elevated' } },
        heart_rate: { value: 79, levels: 'Normal' },
        respiratory_rate: { value: 17, levels: 'Normal' },
        temperature: { value: 98.3, levels: 'Normal' },
      },
      {
        month: 'September',
        year: 2024,
        blood_pressure: { systolic: { value: 144, levels: 'High' }, diastolic: { value: 96, levels: 'High' } },
        heart_rate: { value: 86, levels: 'Normal' },
        respiratory_rate: { value: 20, levels: 'Normal' },
        temperature: { value: 98.9, levels: 'Normal' },
      },
      {
        month: 'October',
        year: 2024,
        blood_pressure: { systolic: { value: 135, levels: 'High' }, diastolic: { value: 89, levels: 'Elevated' } },
        heart_rate: { value: 81, levels: 'Normal' },
        respiratory_rate: { value: 18, levels: 'Normal' },
        temperature: { value: 98.5, levels: 'Normal' },
      },
      {
        month: 'November',
        year: 2024,
        blood_pressure: { systolic: { value: 130, levels: 'Elevated' }, diastolic: { value: 85, levels: 'Elevated' } },
        heart_rate: { value: 78, levels: 'Normal' },
        respiratory_rate: { value: 17, levels: 'Normal' },
        temperature: { value: 98.2, levels: 'Normal' },
      },
      {
        month: 'December',
        year: 2024,
        blood_pressure: { systolic: { value: 128, levels: 'Elevated' }, diastolic: { value: 84, levels: 'Elevated' } },
        heart_rate: { value: 76, levels: 'Normal' },
        respiratory_rate: { value: 16, levels: 'Normal' },
        temperature: { value: 98.1, levels: 'Normal' },
      },
      {
        month: 'January',
        year: 2025,
        blood_pressure: { systolic: { value: 132, levels: 'Elevated' }, diastolic: { value: 86, levels: 'Elevated' } },
        heart_rate: { value: 79, levels: 'Normal' },
        respiratory_rate: { value: 17, levels: 'Normal' },
        temperature: { value: 98.4, levels: 'Normal' },
      },
      {
        month: 'February',
        year: 2025,
        blood_pressure: { systolic: { value: 138, levels: 'High' }, diastolic: { value: 90, levels: 'High' } },
        heart_rate: { value: 82, levels: 'Normal' },
        respiratory_rate: { value: 18, levels: 'Normal' },
        temperature: { value: 98.6, levels: 'Normal' },
      },
      {
        month: 'March',
        year: 2025,
        blood_pressure: { systolic: { value: 134, levels: 'Elevated' }, diastolic: { value: 87, levels: 'Elevated' } },
        heart_rate: { value: 80, levels: 'Normal' },
        respiratory_rate: { value: 17, levels: 'Normal' },
        temperature: { value: 98.3, levels: 'Normal' },
      },
      {
        month: 'April',
        year: 2025,
        blood_pressure: { systolic: { value: 136, levels: 'High' }, diastolic: { value: 89, levels: 'Elevated' } },
        heart_rate: { value: 81, levels: 'Normal' },
        respiratory_rate: { value: 18, levels: 'Normal' },
        temperature: { value: 98.5, levels: 'Normal' },
      },
    ],
    diagnostic_list: [
      { name: 'Hypertension', description: 'Chronic high blood pressure', status: 'Under Observation' },
      { name: 'Hyperlipidemia', description: 'Elevated cholesterol levels', status: 'Under Observation' },
      { name: 'GERD', description: 'Gastroesophageal reflux disease', status: 'Stable' },
    ],
    lab_results: [
      'Blood Test - Lipid Panel',
      'Blood Test - Comprehensive Metabolic Panel',
      'Electrocardiogram (ECG)',
      'Stress Test',
    ],
  },
  {
    name: 'Emily Davis',
    gender: 'Female',
    age: 35,
    profile_picture: '',
    date_of_birth: '11/02/1989',
    phone_number: '(415) 555-7890',
    emergency_contact: '(415) 555-2345',
    insurance_type: 'Aetna Premier',
    diagnosis_history: [
      {
        month: 'May',
        year: 2024,
        blood_pressure: { systolic: { value: 110, levels: 'Normal' }, diastolic: { value: 72, levels: 'Normal' } },
        heart_rate: { value: 68, levels: 'Normal' },
        respiratory_rate: { value: 15, levels: 'Normal' },
        temperature: { value: 98.0, levels: 'Normal' },
      },
      {
        month: 'June',
        year: 2024,
        blood_pressure: { systolic: { value: 112, levels: 'Normal' }, diastolic: { value: 74, levels: 'Normal' } },
        heart_rate: { value: 70, levels: 'Normal' },
        respiratory_rate: { value: 16, levels: 'Normal' },
        temperature: { value: 98.2, levels: 'Normal' },
      },
      {
        month: 'July',
        year: 2024,
        blood_pressure: { systolic: { value: 108, levels: 'Normal' }, diastolic: { value: 70, levels: 'Normal' } },
        heart_rate: { value: 66, levels: 'Normal' },
        respiratory_rate: { value: 14, levels: 'Normal' },
        temperature: { value: 97.9, levels: 'Normal' },
      },
      {
        month: 'August',
        year: 2024,
        blood_pressure: { systolic: { value: 114, levels: 'Normal' }, diastolic: { value: 76, levels: 'Normal' } },
        heart_rate: { value: 72, levels: 'Normal' },
        respiratory_rate: { value: 16, levels: 'Normal' },
        temperature: { value: 98.3, levels: 'Normal' },
      },
      {
        month: 'September',
        year: 2024,
        blood_pressure: { systolic: { value: 116, levels: 'Normal' }, diastolic: { value: 75, levels: 'Normal' } },
        heart_rate: { value: 71, levels: 'Normal' },
        respiratory_rate: { value: 15, levels: 'Normal' },
        temperature: { value: 98.1, levels: 'Normal' },
      },
      {
        month: 'October',
        year: 2024,
        blood_pressure: { systolic: { value: 111, levels: 'Normal' }, diastolic: { value: 73, levels: 'Normal' } },
        heart_rate: { value: 69, levels: 'Normal' },
        respiratory_rate: { value: 15, levels: 'Normal' },
        temperature: { value: 98.0, levels: 'Normal' },
      },
      {
        month: 'November',
        year: 2024,
        blood_pressure: { systolic: { value: 109, levels: 'Normal' }, diastolic: { value: 71, levels: 'Normal' } },
        heart_rate: { value: 67, levels: 'Normal' },
        respiratory_rate: { value: 14, levels: 'Normal' },
        temperature: { value: 97.8, levels: 'Normal' },
      },
      {
        month: 'December',
        year: 2024,
        blood_pressure: { systolic: { value: 113, levels: 'Normal' }, diastolic: { value: 74, levels: 'Normal' } },
        heart_rate: { value: 70, levels: 'Normal' },
        respiratory_rate: { value: 16, levels: 'Normal' },
        temperature: { value: 98.2, levels: 'Normal' },
      },
      {
        month: 'January',
        year: 2025,
        blood_pressure: { systolic: { value: 115, levels: 'Normal' }, diastolic: { value: 76, levels: 'Normal' } },
        heart_rate: { value: 72, levels: 'Normal' },
        respiratory_rate: { value: 16, levels: 'Normal' },
        temperature: { value: 98.4, levels: 'Normal' },
      },
      {
        month: 'February',
        year: 2025,
        blood_pressure: { systolic: { value: 107, levels: 'Normal' }, diastolic: { value: 69, levels: 'Normal' } },
        heart_rate: { value: 65, levels: 'Normal' },
        respiratory_rate: { value: 14, levels: 'Normal' },
        temperature: { value: 97.7, levels: 'Normal' },
      },
      {
        month: 'March',
        year: 2025,
        blood_pressure: { systolic: { value: 112, levels: 'Normal' }, diastolic: { value: 73, levels: 'Normal' } },
        heart_rate: { value: 69, levels: 'Normal' },
        respiratory_rate: { value: 15, levels: 'Normal' },
        temperature: { value: 98.1, levels: 'Normal' },
      },
      {
        month: 'April',
        year: 2025,
        blood_pressure: { systolic: { value: 110, levels: 'Normal' }, diastolic: { value: 72, levels: 'Normal' } },
        heart_rate: { value: 68, levels: 'Normal' },
        respiratory_rate: { value: 15, levels: 'Normal' },
        temperature: { value: 98.0, levels: 'Normal' },
      },
    ],
    diagnostic_list: [
      { name: 'Migraine', description: 'Recurrent moderate to severe headaches', status: 'Under Observation' },
      { name: 'Iron Deficiency Anemia', description: 'Low iron levels causing fatigue', status: 'Stable' },
    ],
    lab_results: [
      'Blood Test - Complete Blood Count',
      'Blood Test - Iron Panel',
      'Vitamin D Level',
    ],
  },
  {
    name: 'Robert Wilson',
    gender: 'Male',
    age: 62,
    profile_picture: '',
    date_of_birth: '05/19/1963',
    phone_number: '(415) 555-4567',
    emergency_contact: '(415) 555-8901',
    insurance_type: 'Medicare Advantage',
    diagnosis_history: [
      {
        month: 'May',
        year: 2024,
        blood_pressure: { systolic: { value: 150, levels: 'High' }, diastolic: { value: 95, levels: 'High' } },
        heart_rate: { value: 88, levels: 'Normal' },
        respiratory_rate: { value: 20, levels: 'Normal' },
        temperature: { value: 98.8, levels: 'Normal' },
      },
      {
        month: 'June',
        year: 2024,
        blood_pressure: { systolic: { value: 148, levels: 'High' }, diastolic: { value: 93, levels: 'High' } },
        heart_rate: { value: 86, levels: 'Normal' },
        respiratory_rate: { value: 19, levels: 'Normal' },
        temperature: { value: 98.6, levels: 'Normal' },
      },
      {
        month: 'July',
        year: 2024,
        blood_pressure: { systolic: { value: 155, levels: 'High' }, diastolic: { value: 98, levels: 'High' } },
        heart_rate: { value: 90, levels: 'Normal' },
        respiratory_rate: { value: 21, levels: 'Normal' },
        temperature: { value: 99.0, levels: 'Normal' },
      },
      {
        month: 'August',
        year: 2024,
        blood_pressure: { systolic: { value: 145, levels: 'High' }, diastolic: { value: 91, levels: 'High' } },
        heart_rate: { value: 85, levels: 'Normal' },
        respiratory_rate: { value: 19, levels: 'Normal' },
        temperature: { value: 98.5, levels: 'Normal' },
      },
      {
        month: 'September',
        year: 2024,
        blood_pressure: { systolic: { value: 152, levels: 'High' }, diastolic: { value: 96, levels: 'High' } },
        heart_rate: { value: 89, levels: 'Normal' },
        respiratory_rate: { value: 20, levels: 'Normal' },
        temperature: { value: 98.9, levels: 'Normal' },
      },
      {
        month: 'October',
        year: 2024,
        blood_pressure: { systolic: { value: 147, levels: 'High' }, diastolic: { value: 92, levels: 'High' } },
        heart_rate: { value: 87, levels: 'Normal' },
        respiratory_rate: { value: 19, levels: 'Normal' },
        temperature: { value: 98.7, levels: 'Normal' },
      },
      {
        month: 'November',
        year: 2024,
        blood_pressure: { systolic: { value: 143, levels: 'High' }, diastolic: { value: 90, levels: 'High' } },
        heart_rate: { value: 84, levels: 'Normal' },
        respiratory_rate: { value: 18, levels: 'Normal' },
        temperature: { value: 98.4, levels: 'Normal' },
      },
      {
        month: 'December',
        year: 2024,
        blood_pressure: { systolic: { value: 140, levels: 'High' }, diastolic: { value: 88, levels: 'Elevated' } },
        heart_rate: { value: 82, levels: 'Normal' },
        respiratory_rate: { value: 18, levels: 'Normal' },
        temperature: { value: 98.3, levels: 'Normal' },
      },
      {
        month: 'January',
        year: 2025,
        blood_pressure: { systolic: { value: 146, levels: 'High' }, diastolic: { value: 92, levels: 'High' } },
        heart_rate: { value: 86, levels: 'Normal' },
        respiratory_rate: { value: 19, levels: 'Normal' },
        temperature: { value: 98.6, levels: 'Normal' },
      },
      {
        month: 'February',
        year: 2025,
        blood_pressure: { systolic: { value: 153, levels: 'High' }, diastolic: { value: 97, levels: 'High' } },
        heart_rate: { value: 91, levels: 'Normal' },
        respiratory_rate: { value: 21, levels: 'Normal' },
        temperature: { value: 99.1, levels: 'Normal' },
      },
      {
        month: 'March',
        year: 2025,
        blood_pressure: { systolic: { value: 149, levels: 'High' }, diastolic: { value: 94, levels: 'High' } },
        heart_rate: { value: 88, levels: 'Normal' },
        respiratory_rate: { value: 20, levels: 'Normal' },
        temperature: { value: 98.8, levels: 'Normal' },
      },
      {
        month: 'April',
        year: 2025,
        blood_pressure: { systolic: { value: 151, levels: 'High' }, diastolic: { value: 96, levels: 'High' } },
        heart_rate: { value: 90, levels: 'Normal' },
        respiratory_rate: { value: 20, levels: 'Normal' },
        temperature: { value: 99.0, levels: 'Normal' },
      },
    ],
    diagnostic_list: [
      { name: 'Hypertension', description: 'Chronic high blood pressure', status: 'Under Observation' },
      { name: 'Coronary Artery Disease', description: 'Narrowing of coronary arteries', status: 'Under Observation' },
      { name: 'Osteoarthritis', description: 'Degenerative joint disease', status: 'Stable' },
      { name: 'Benign Prostatic Hyperplasia', description: 'Enlarged prostate', status: 'Stable' },
    ],
    lab_results: [
      'Blood Test - Complete Blood Count',
      'Blood Test - Comprehensive Metabolic Panel',
      'Blood Test - Lipid Panel',
      'Electrocardiogram (ECG)',
      'Echocardiogram',
      'Prostate-Specific Antigen (PSA)',
    ],
  },
  {
    name: 'Sarah Martinez',
    gender: 'Female',
    age: 31,
    profile_picture: '',
    date_of_birth: '07/08/1993',
    phone_number: '(415) 555-6789',
    emergency_contact: '(415) 555-0123',
    insurance_type: 'Cigna Health Plus',
    diagnosis_history: [
      {
        month: 'May',
        year: 2024,
        blood_pressure: { systolic: { value: 115, levels: 'Normal' }, diastolic: { value: 75, levels: 'Normal' } },
        heart_rate: { value: 70, levels: 'Normal' },
        respiratory_rate: { value: 16, levels: 'Normal' },
        temperature: { value: 98.2, levels: 'Normal' },
      },
      {
        month: 'June',
        year: 2024,
        blood_pressure: { systolic: { value: 118, levels: 'Normal' }, diastolic: { value: 77, levels: 'Normal' } },
        heart_rate: { value: 72, levels: 'Normal' },
        respiratory_rate: { value: 17, levels: 'Normal' },
        temperature: { value: 98.4, levels: 'Normal' },
      },
      {
        month: 'July',
        year: 2024,
        blood_pressure: { systolic: { value: 120, levels: 'Normal' }, diastolic: { value: 79, levels: 'Normal' } },
        heart_rate: { value: 74, levels: 'Normal' },
        respiratory_rate: { value: 17, levels: 'Normal' },
        temperature: { value: 98.5, levels: 'Normal' },
      },
      {
        month: 'August',
        year: 2024,
        blood_pressure: { systolic: { value: 117, levels: 'Normal' }, diastolic: { value: 76, levels: 'Normal' } },
        heart_rate: { value: 71, levels: 'Normal' },
        respiratory_rate: { value: 16, levels: 'Normal' },
        temperature: { value: 98.3, levels: 'Normal' },
      },
      {
        month: 'September',
        year: 2024,
        blood_pressure: { systolic: { value: 122, levels: 'Elevated' }, diastolic: { value: 80, levels: 'Normal' } },
        heart_rate: { value: 75, levels: 'Normal' },
        respiratory_rate: { value: 18, levels: 'Normal' },
        temperature: { value: 98.6, levels: 'Normal' },
      },
      {
        month: 'October',
        year: 2024,
        blood_pressure: { systolic: { value: 119, levels: 'Normal' }, diastolic: { value: 78, levels: 'Normal' } },
        heart_rate: { value: 73, levels: 'Normal' },
        respiratory_rate: { value: 17, levels: 'Normal' },
        temperature: { value: 98.4, levels: 'Normal' },
      },
      {
        month: 'November',
        year: 2024,
        blood_pressure: { systolic: { value: 116, levels: 'Normal' }, diastolic: { value: 74, levels: 'Normal' } },
        heart_rate: { value: 69, levels: 'Normal' },
        respiratory_rate: { value: 15, levels: 'Normal' },
        temperature: { value: 98.1, levels: 'Normal' },
      },
      {
        month: 'December',
        year: 2024,
        blood_pressure: { systolic: { value: 121, levels: 'Elevated' }, diastolic: { value: 81, levels: 'Normal' } },
        heart_rate: { value: 76, levels: 'Normal' },
        respiratory_rate: { value: 18, levels: 'Normal' },
        temperature: { value: 98.7, levels: 'Normal' },
      },
      {
        month: 'January',
        year: 2025,
        blood_pressure: { systolic: { value: 114, levels: 'Normal' }, diastolic: { value: 73, levels: 'Normal' } },
        heart_rate: { value: 68, levels: 'Normal' },
        respiratory_rate: { value: 15, levels: 'Normal' },
        temperature: { value: 98.0, levels: 'Normal' },
      },
      {
        month: 'February',
        year: 2025,
        blood_pressure: { systolic: { value: 123, levels: 'Elevated' }, diastolic: { value: 82, levels: 'Elevated' } },
        heart_rate: { value: 77, levels: 'Normal' },
        respiratory_rate: { value: 18, levels: 'Normal' },
        temperature: { value: 98.6, levels: 'Normal' },
      },
      {
        month: 'March',
        year: 2025,
        blood_pressure: { systolic: { value: 117, levels: 'Normal' }, diastolic: { value: 76, levels: 'Normal' } },
        heart_rate: { value: 71, levels: 'Normal' },
        respiratory_rate: { value: 16, levels: 'Normal' },
        temperature: { value: 98.2, levels: 'Normal' },
      },
      {
        month: 'April',
        year: 2025,
        blood_pressure: { systolic: { value: 120, levels: 'Normal' }, diastolic: { value: 79, levels: 'Normal' } },
        heart_rate: { value: 74, levels: 'Normal' },
        respiratory_rate: { value: 17, levels: 'Normal' },
        temperature: { value: 98.4, levels: 'Normal' },
      },
    ],
    diagnostic_list: [
      { name: 'Hypothyroidism', description: 'Underactive thyroid gland', status: 'Stable' },
      { name: 'Vitamin D Deficiency', description: 'Low vitamin D levels', status: 'Resolved' },
    ],
    lab_results: [
      'Blood Test - Thyroid Panel',
      'Blood Test - Vitamin D Level',
      'Blood Test - Complete Blood Count',
    ],
  },
  {
    name: 'David Thompson',
    gender: 'Male',
    age: 52,
    profile_picture: '',
    date_of_birth: '01/25/1973',
    phone_number: '(415) 555-3456',
    emergency_contact: '(415) 555-7890',
    insurance_type: 'United Healthcare',
    diagnosis_history: [
      {
        month: 'May',
        year: 2024,
        blood_pressure: { systolic: { value: 135, levels: 'Elevated' }, diastolic: { value: 87, levels: 'Elevated' } },
        heart_rate: { value: 78, levels: 'Normal' },
        respiratory_rate: { value: 17, levels: 'Normal' },
        temperature: { value: 98.4, levels: 'Normal' },
      },
      {
        month: 'June',
        year: 2024,
        blood_pressure: { systolic: { value: 132, levels: 'Elevated' }, diastolic: { value: 85, levels: 'Elevated' } },
        heart_rate: { value: 76, levels: 'Normal' },
        respiratory_rate: { value: 16, levels: 'Normal' },
        temperature: { value: 98.2, levels: 'Normal' },
      },
      {
        month: 'July',
        year: 2024,
        blood_pressure: { systolic: { value: 138, levels: 'High' }, diastolic: { value: 89, levels: 'Elevated' } },
        heart_rate: { value: 80, levels: 'Normal' },
        respiratory_rate: { value: 18, levels: 'Normal' },
        temperature: { value: 98.6, levels: 'Normal' },
      },
      {
        month: 'August',
        year: 2024,
        blood_pressure: { systolic: { value: 130, levels: 'Elevated' }, diastolic: { value: 84, levels: 'Elevated' } },
        heart_rate: { value: 75, levels: 'Normal' },
        respiratory_rate: { value: 16, levels: 'Normal' },
        temperature: { value: 98.1, levels: 'Normal' },
      },
      {
        month: 'September',
        year: 2024,
        blood_pressure: { systolic: { value: 140, levels: 'High' }, diastolic: { value: 91, levels: 'High' } },
        heart_rate: { value: 82, levels: 'Normal' },
        respiratory_rate: { value: 19, levels: 'Normal' },
        temperature: { value: 98.7, levels: 'Normal' },
      },
      {
        month: 'October',
        year: 2024,
        blood_pressure: { systolic: { value: 133, levels: 'Elevated' }, diastolic: { value: 86, levels: 'Elevated' } },
        heart_rate: { value: 77, levels: 'Normal' },
        respiratory_rate: { value: 17, levels: 'Normal' },
        temperature: { value: 98.3, levels: 'Normal' },
      },
      {
        month: 'November',
        year: 2024,
        blood_pressure: { systolic: { value: 128, levels: 'Elevated' }, diastolic: { value: 83, levels: 'Elevated' } },
        heart_rate: { value: 74, levels: 'Normal' },
        respiratory_rate: { value: 16, levels: 'Normal' },
        temperature: { value: 98.0, levels: 'Normal' },
      },
      {
        month: 'December',
        year: 2024,
        blood_pressure: { systolic: { value: 136, levels: 'High' }, diastolic: { value: 88, levels: 'Elevated' } },
        heart_rate: { value: 79, levels: 'Normal' },
        respiratory_rate: { value: 18, levels: 'Normal' },
        temperature: { value: 98.5, levels: 'Normal' },
      },
      {
        month: 'January',
        year: 2025,
        blood_pressure: { systolic: { value: 134, levels: 'Elevated' }, diastolic: { value: 86, levels: 'Elevated' } },
        heart_rate: { value: 77, levels: 'Normal' },
        respiratory_rate: { value: 17, levels: 'Normal' },
        temperature: { value: 98.3, levels: 'Normal' },
      },
      {
        month: 'February',
        year: 2025,
        blood_pressure: { systolic: { value: 142, levels: 'High' }, diastolic: { value: 90, levels: 'High' } },
        heart_rate: { value: 83, levels: 'Normal' },
        respiratory_rate: { value: 19, levels: 'Normal' },
        temperature: { value: 98.8, levels: 'Normal' },
      },
      {
        month: 'March',
        year: 2025,
        blood_pressure: { systolic: { value: 131, levels: 'Elevated' }, diastolic: { value: 84, levels: 'Elevated' } },
        heart_rate: { value: 76, levels: 'Normal' },
        respiratory_rate: { value: 16, levels: 'Normal' },
        temperature: { value: 98.2, levels: 'Normal' },
      },
      {
        month: 'April',
        year: 2025,
        blood_pressure: { systolic: { value: 137, levels: 'High' }, diastolic: { value: 88, levels: 'Elevated' } },
        heart_rate: { value: 80, levels: 'Normal' },
        respiratory_rate: { value: 18, levels: 'Normal' },
        temperature: { value: 98.5, levels: 'Normal' },
      },
    ],
    diagnostic_list: [
      { name: 'Type 2 Diabetes', description: 'Insulin resistance and elevated blood sugar', status: 'Under Observation' },
      { name: 'Hypertension', description: 'Chronic high blood pressure', status: 'Under Observation' },
      { name: 'Sleep Apnea', description: 'Obstructive sleep apnea syndrome', status: 'Stable' },
    ],
    lab_results: [
      'Blood Test - Hemoglobin A1C',
      'Blood Test - Comprehensive Metabolic Panel',
      'Sleep Study Report',
      'Blood Test - Lipid Panel',
    ],
  },
];

export default mockPatients;